pipeline {
    agent any
    triggers {
        cron('*/15 * * * *')
    }
    stages {
        stage('Automated Build') {
            steps {
                echo 'Building from cron trigger...'
            }
        }
    }
}