pipeline {
    agent any

    options {
        timeout(time: 1, unit: 'MINUTES')
    }
    
    stages {
        stage('Stage timeout') {
            steps {
                sleep 70
            }
        }
    }
}