pipeline {
    agent any
    stages {
        stage('Primero') {
            steps {
                echo 'Stage 1'
            }
        }

        stage('Segundo') {
            steps {
                echo 'Stage 2'
            }
        }

        stage('Tercero') {
            steps {
                echo 'Stage 3'
                echo 'Stage 3.1'
                echo 'Stage 3.2'
            }
        }
    }    
}