pipeline {
    agent any

    tools {
        nodejs 'node-20'
    }
    
    stages {
        stage('Stage tools-node') {
            steps {
                sh 'node -v'
                sh 'npm -v'
            }
        }
    }
}